POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "user2",
    "name": "user2",
    "password": "password"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "te",
    "name": "his_name",
    "password": "some_random_nonsense"
}


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test_user",
    "name": "hi",
    "password": "some_random_nonsense"
}


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test_user",
    "name": "hi",
    "password": "so"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test_user",
    "name": "hi"
}